### ISSUE TITLE
Auxiliary parameter support (i.e. Measurement Class support)

### ISSUE THREAD

**Issue by nicmostert** [HorizonsRC/hydrobot#125]
After working on #111 I realised that there is an abstraction that we can add that would simplify everything a great deal. 

A Measurement Class would be a good thing to have. A Measurement would have the standard, quality and check data sitting on it, along with range, site, and everything that is needed to manage and maintain a single measurement from a single site. Then a Processor might have a Main Measurement (the measurement being processed/affected/QC'd), and many Aux Measurements. These Aux Measurements will have the optional ability to specify their own sites, or inherit site from their main measurement, etc, which would then tackle #47. Maybe it's even on another .hts file, like when it is from another processing stage, which would address #43. 

In the config.yaml they could be specified like this:
```
aux_measurements:
  1:
    site: "Site Name"
    standard_hts_filename: "otherhts.hts"
    standard_measurement_name: "Measurement Name [Data Source Name]"
```

Everything not in the config can be inherited from the main measurement.
